language: python
python:
  - "3.8"
env:
  - DJANGO_SETTINGS_MODULE="core.settings"
services:
  - postgresql
  - docker
install:
  - pipenv install
before_script: 
  - pip install docker-compose
script:
  - export SECRET_KEY="test"
  - docker-compose run web sh -c "python manage.py test"