language: python
python:
  - "3.8"
env:
  - DJANGO_SETTINGS_MODULE="core.settings"
services:
  - postgresql
  - docker
before_script: 
  - pip install docker-compose
  - touch .env
  - echo SECRET_KEY=$SECRET_KEY >> .env
script:
  - docker-compose run web sh -c "python manage.py test"