version: '3.8'

services:
    web:
        build: .
        command: python /django-bestMovies/manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/django-bestMovies
        ports:
            - 8000:8000
        depends_on:
            - db
        environment: 
            - "SECRET_KEY=${SECRET_KEY}"
    db:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes: 
    postgres_data: