# Generated by Django 3.2.7 on 2021-09-04 01:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
                ('entity', models.TextField()),
                ('winner', models.BooleanField()),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
